# Generated by Django 3.0.7 on 2020-08-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_middata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('ErNo', models.CharField(max_length=20)),
                ('BirthDate', models.DateField()),
            ],
        ),
    ]
